### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Trilarion** [eguneys/supaxl#1]
It seems this project has no license information included with the sources. What is the license of the code and the artwork? Could information about it be included in the repository?

**Comment by eguneys** [comment]
I don't own the artwork, though I added a LICENSE. thank you for your interest.

**Comment by Trilarion** [comment]
Thanks for adding a license for the code. For the artwork which seems to be from the original Supaplex, one could ask the original authors for a license or one could try to replace the artwork piece by piece.
